syntax = "proto3";

package item;

service ItemService {
  rpc GetItems (GetItemsRequest) returns (GetItemsResponse) {}
  rpc AddItems (AddItemsRequest) returns (AddItemsResponse) {}
  rpc ClearItems (ClearItemsRequest) returns (ClearItemsResponse) {}
}

message Item {
  uint64 id = 1;
  string name = 2;
  float value = 3;
  optional string details = 4;
}

message ItemInput {
  string name = 1;
  float value = 2;
  optional string details = 3;
}

message GetItemsRequest {
  repeated uint64 item_ids = 1;
}

message GetItemsResponse {
  repeated Item items = 1;
}

message AddItemsRequest {
  repeated ItemInput items = 1;
}

message AddItemsResponse {
  repeated Item items = 1;
}

message ClearItemsRequest {
}

message ClearItemsResponse {
}