  syntax = "proto3";

package tutorial;

option java_package = "sr.proto";
option java_outer_classname = "AddressBookProtos";

message Person {
  string name = 1;
  int32 id = 2;
  string email = 3;
  double incomePercentage = 4;

  enum PhoneType {
    MOBILE = 0;
    HOME = 1;
    WORK = 2;
  }

  message PhoneNumber {
    string number = 1;
    PhoneType type = 2;
  }

  repeated PhoneNumber phones = 5;

  //Dodaj do definicji person.proto nową (dowolną) wiadomość zawierającą sekwencję liczb niecałkowitych
  //(oznaczającą np. wysokość przychodów osoby w ostatnich miesiącach). Użyj słowa kluczowego repeated.
  //Ponownie skompiluj i przeprowadź serializację nowej wersji wiadomości zawierającej np. trzy liczby w
  //sekwencji.
  repeated double IncomeHistory = 6;
}

message AddressBook {
  repeated Person people = 1;
}

